// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/DynamicCom/A.vue')['default']
    A1: typeof import('./src/components/Mitt/A1.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    B: typeof import('./src/components/DynamicCom/B.vue')['default']
    B1: typeof import('./src/components/Mitt/B1.vue')['default']
    BindStyle: typeof import('./src/components/BindStyle/index.vue')['default']
    Bus: typeof import('./src/components/Bus/index.vue')['default']
    BusEmit: typeof import('./src/components/Bus/BusEmit.vue')['default']
    BusOn: typeof import('./src/components/Bus/BusOn.vue')['default']
    Directive: typeof import('./src/components/Directive/index.vue')['default']
    DynamicCom: typeof import('./src/components/DynamicCom/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    Mitt: typeof import('./src/components/Mitt/index.vue')['default']
    Modal: typeof import('./src/components/Teleport/Modal.vue')['default']
    NextTick: typeof import('./src/components/NextTick/index.vue')['default']
    PropsChild: typeof import('./src/components/PropsCom/PropsChild.vue')['default']
    PropsCom: typeof import('./src/components/PropsCom/index.vue')['default']
    ProvideOrInject: typeof import('./src/components/ProvideOrInject/index.vue')['default']
    ReactiveDemo: typeof import('./src/components/reactiveDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreCom: typeof import('./src/components/StoreCom/index.vue')['default']
    Teleport: typeof import('./src/components/Teleport/index.vue')['default']
    TorefDemo: typeof import('./src/components/torefDemo.vue')['default']
  }
}
