// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./components/DynamicCom/A.vue')['default']
    A1: typeof import('./components/Mitt/A1.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AInput: typeof import('ant-design-vue/es')['Input']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    ATimeRangePicker: typeof import('ant-design-vue/es')['TimeRangePicker']
    B: typeof import('./components/DynamicCom/B.vue')['default']
    B1: typeof import('./components/Mitt/B1.vue')['default']
    BindStyle: typeof import('./components/BindStyle/index.vue')['default']
    Bus: typeof import('./components/Bus/index.vue')['default']
    BusEmit: typeof import('./components/Bus/BusEmit.vue')['default']
    BusOn: typeof import('./components/Bus/BusOn.vue')['default']
    Directive: typeof import('./components/Directive/index.vue')['default']
    DynamicCom: typeof import('./components/DynamicCom/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Mitt: typeof import('./components/Mitt/index.vue')['default']
    Modal: typeof import('./components/Teleport/Modal.vue')['default']
    NextTick: typeof import('./components/NextTick/index.vue')['default']
    PropsChild: typeof import('./components/PropsCom/PropsChild.vue')['default']
    PropsCom: typeof import('./components/PropsCom/index.vue')['default']
    ProvideOrInject: typeof import('./components/ProvideOrInject/index.vue')['default']
    ReactiveDemo: typeof import('./components/reactiveDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreCom: typeof import('./components/StoreCom/index.vue')['default']
    Teleport: typeof import('./components/Teleport/index.vue')['default']
    TorefDemo: typeof import('./components/torefDemo.vue')['default']
  }
}
